modLoader="javafml" #mandatory
loaderVersion="[40,)"

[[mods]]
modId="buycraftx"
version="${file.jarVersion}"
displayName="BuycraftX"
displayURL="https://www.tebex.io/"
authors="Tebex, theminecoder"
description='''
Forge version of the BuycraftX plugin for servers'''

[[dependencies.buycraftx]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"