modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory (24 is current forge version)
license="All Rights Reserved By Tebex"

[[mods]]
modId="buycraftx"
version="${file.jarVersion}"
displayName="BuycraftX"
displayURL="https://www.tebex.io/"
authors="Tebex, theminecoder"
description='''
Forge version of the BuycraftX plugin for servers'''

[[dependencies.buycraftx]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"