package ca.skynetcloud.electricfencemod.init;

import ca.skynetcloud.electricfencemod.Electricfencemod;
import ca.skynetcloud.electricfencemod.items.WrenchTool;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemInit {

    public static DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Electricfencemod.MODID);
    public static RegistryObject<Item> ElectricCabinet;
    public static RegistryObject<Item> ElectricFence;
    public static RegistryObject<Item> ElectricFenceTop;
    public static RegistryObject<Item> ElectricFenceGate;
    public static RegistryObject<Item> WHITE_Electric_Fence;
    public static RegistryObject<Item> ORANGE_Electric_Fence;
    public static RegistryObject<Item> MAGENTA_Electric_Fence;
    public static RegistryObject<Item> LIGHT_BLUE_Electric_Fence;
    public static RegistryObject<Item> YELLOW_Electric_Fence;
    public static RegistryObject<Item> LIME_Electric_Fence;
    public static RegistryObject<Item> PINK_Electric_Fence;
    public static RegistryObject<Item> GRAY_Electric_Fence;
    public static RegistryObject<Item> LIGHT_GRAY_Electric_Fence;
    public static RegistryObject<Item> CYAN_Electric_Fence;
    public static RegistryObject<Item> PURPLE_Electric_Fence;
    public static RegistryObject<Item> BLUE_Electric_Fence;
    public static RegistryObject<Item> BROWN_Electric_Fence;
    public static RegistryObject<Item> GREEN_Electric_Fence;
    public static RegistryObject<Item> RED_Electric_Fence;
    public static RegistryObject<Item> BLACK_Electric_Fence;
    public static RegistryObject<Item> WHITE_Electric_FenceTop;
    public static RegistryObject<Item> ORANGE_Electric_FenceTop;
    public static RegistryObject<Item> MAGENTA_Electric_FenceTop;
    public static RegistryObject<Item> LIGHT_BLUE_Electric_FenceTop;
    public static RegistryObject<Item> YELLOW_Electric_FenceTop;
    public static RegistryObject<Item> LIME_Electric_FenceTop;
    public static RegistryObject<Item> PINK_Electric_FenceTop;
    public static RegistryObject<Item> GRAY_Electric_FenceTop;
    public static RegistryObject<Item> LIGHT_GRAY_Electric_FenceTop;
    public static RegistryObject<Item> CYAN_Electric_FenceTop;
    public static RegistryObject<Item> PURPLE_Electric_FenceTop;
    public static RegistryObject<Item> BLUE_Electric_FenceTop;
    public static RegistryObject<Item> BROWN_Electric_FenceTop;
    public static RegistryObject<Item> GREEN_Electric_FenceTop;
    public static RegistryObject<Item> RED_Electric_FenceTop;
    public static RegistryObject<Item> BLACK_Electric_FenceTop;
    public static RegistryObject<Item> WHITE_Electric_FenceGate;
    public static RegistryObject<Item> ORANGE_Electric_FenceGate;
    public static RegistryObject<Item> MAGENTA_Electric_FenceGate;
    public static RegistryObject<Item> LIGHT_BLUE_Electric_FenceGate;
    public static RegistryObject<Item> YELLOW_Electric_FenceGate;
    public static RegistryObject<Item> LIME_Electric_FenceGate;
    public static RegistryObject<Item> PINK_Electric_FenceGate;
    public static RegistryObject<Item> GRAY_Electric_FenceGate;
    public static RegistryObject<Item> LIGHT_GRAY_Electric_FenceGate;
    public static RegistryObject<Item> CYAN_Electric_FenceGate;
    public static RegistryObject<Item> PURPLE_Electric_FenceGate;
    public static RegistryObject<Item> BLUE_Electric_FenceGate;
    public static RegistryObject<Item> BROWN_Electric_FenceGate;
    public static RegistryObject<Item> GREEN_Electric_FenceGate;
    public static RegistryObject<Item> RED_Electric_FenceGate;
    public static RegistryObject<Item> BLACK_Electric_FenceGate;
    public static RegistryObject<Item> wrench_tool;

    static {
        BLACK_Electric_FenceGate = ITEMS.register("black_electric_fence_gate", () -> new BlockItem(BlockInit.BLACK_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        RED_Electric_FenceGate = ITEMS.register("red_electric_fence_gate", () -> new BlockItem(BlockInit.RED_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GREEN_Electric_FenceGate = ITEMS.register("green_electric_fence_gate", () -> new BlockItem(BlockInit.GREEN_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        wrench_tool = ITEMS.register("wrench_tool", () -> new WrenchTool());
        BROWN_Electric_FenceGate = ITEMS.register("brown_electric_fence_gate", () -> new BlockItem(BlockInit.BROWN_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BLUE_Electric_FenceGate = ITEMS.register("blue_electric_fence_gate", () -> new BlockItem(BlockInit.BLUE_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PURPLE_Electric_FenceGate = ITEMS.register("purple_electric_fence_gate", () -> new BlockItem(BlockInit.PURPLE_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        CYAN_Electric_FenceGate = ITEMS.register("cyan_electric_fence_gate", () -> new BlockItem(BlockInit.CYAN_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_GRAY_Electric_FenceGate = ITEMS.register("light_gray_electric_fence_gate", () -> new BlockItem(BlockInit.LIGHT_GRAY_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GRAY_Electric_FenceGate = ITEMS.register("gray_electric_fence_gate", () -> new BlockItem(BlockInit.GRAY_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PINK_Electric_FenceGate = ITEMS.register("pink_electric_fence_gate", () -> new BlockItem(BlockInit.PINK_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIME_Electric_FenceGate = ITEMS.register("lime_electric_fence_gate", () -> new BlockItem(BlockInit.LIME_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        YELLOW_Electric_FenceGate = ITEMS.register("yellow_electric_fence_gate", () -> new BlockItem(BlockInit.YELLOW_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_BLUE_Electric_FenceGate = ITEMS.register("light_blue_electric_fence_gate", () -> new BlockItem(BlockInit.LIGHT_BLUE_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        MAGENTA_Electric_FenceGate = ITEMS.register("magenta_electric_fence_gate", () -> new BlockItem(BlockInit.MAGENTA_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ORANGE_Electric_FenceGate = ITEMS.register("orange_electric_fence_gate", () -> new BlockItem(BlockInit.ORANGE_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        WHITE_Electric_FenceGate = ITEMS.register("white_electric_fence_gate", () -> new BlockItem(BlockInit.WHITE_Electric_FenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BLACK_Electric_FenceTop = ITEMS.register("black_electric_fence_top", () -> new BlockItem(BlockInit.BLACK_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        RED_Electric_FenceTop = ITEMS.register("red_electric_fence_top", () -> new BlockItem(BlockInit.RED_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GREEN_Electric_FenceTop = ITEMS.register("green_electric_fence_top", () -> new BlockItem(BlockInit.GREEN_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BROWN_Electric_FenceTop = ITEMS.register("brown_electric_fence_top", () -> new BlockItem(BlockInit.BROWN_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BLUE_Electric_FenceTop = ITEMS.register("blue_electric_fence_top", () -> new BlockItem(BlockInit.BLUE_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PURPLE_Electric_FenceTop = ITEMS.register("purple_electric_fence_top", () -> new BlockItem(BlockInit.PURPLE_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        CYAN_Electric_FenceTop = ITEMS.register("cyan_electric_fence_top", () -> new BlockItem(BlockInit.CYAN_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_GRAY_Electric_FenceTop = ITEMS.register("light_electric_fence_top", () -> new BlockItem(BlockInit.LIGHT_GRAY_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GRAY_Electric_FenceTop = ITEMS.register("gray_electric_fence_top", () -> new BlockItem(BlockInit.GRAY_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PINK_Electric_FenceTop = ITEMS.register("pink_electric_fence_top", () -> new BlockItem(BlockInit.PINK_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIME_Electric_FenceTop = ITEMS.register("lime_electric_fence_top", () -> new BlockItem(BlockInit.LIME_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        YELLOW_Electric_FenceTop = ITEMS.register("yellow_electric_fence_top", () -> new BlockItem(BlockInit.YELLOW_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_BLUE_Electric_FenceTop = ITEMS.register("light_blue_electric_fence_top", () -> new BlockItem(BlockInit.LIGHT_BLUE_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        MAGENTA_Electric_FenceTop = ITEMS.register("magenta_electric_fence_top", () -> new BlockItem(BlockInit.MAGENTA_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ORANGE_Electric_FenceTop = ITEMS.register("orange_electric_fence_top", () -> new BlockItem(BlockInit.ORANGE_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        WHITE_Electric_FenceTop = ITEMS.register("white_electric_fence_top", () -> new BlockItem(BlockInit.WHITE_Electric_FenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ElectricCabinet = ITEMS.register("electrical_cabinet", () -> new BlockItem(BlockInit.electrical_cabinet.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ElectricFenceGate = ITEMS.register("electric_fence_gate", () -> new BlockItem(BlockInit.ElectricFenceGate.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ElectricFenceTop = ITEMS.register("electric_fence_top", () -> new BlockItem(BlockInit.ElectricFenceTop.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ElectricFence = ITEMS.register("electric_fence", () -> new BlockItem(BlockInit.ElectricFence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BLACK_Electric_Fence = ITEMS.register("black_electric_fence", () -> new BlockItem(BlockInit.BLACK_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        RED_Electric_Fence = ITEMS.register("red_electric_fence", () -> new BlockItem(BlockInit.RED_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GREEN_Electric_Fence = ITEMS.register("green_electric_fence", () -> new BlockItem(BlockInit.GREEN_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BROWN_Electric_Fence = ITEMS.register("brown_electric_fence", () -> new BlockItem(BlockInit.BROWN_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        BLUE_Electric_Fence = ITEMS.register("blue_electric_fence", () -> new BlockItem(BlockInit.BLUE_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PURPLE_Electric_Fence = ITEMS.register("purple_electric_fence", () -> new BlockItem(BlockInit.PURPLE_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        CYAN_Electric_Fence = ITEMS.register("cyan_electric_fence", () -> new BlockItem(BlockInit.CYAN_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_GRAY_Electric_Fence = ITEMS.register("light_gray_electric_fence", () -> new BlockItem(BlockInit.LIGHT_GRAY_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        GRAY_Electric_Fence = ITEMS.register("gray_electric_fence", () -> new BlockItem(BlockInit.GRAY_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        PINK_Electric_Fence = ITEMS.register("pink_electric_fence", () -> new BlockItem(BlockInit.PINK_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        WHITE_Electric_Fence = ITEMS.register("white_electric_fence", () -> new BlockItem(BlockInit.WHITE_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        ORANGE_Electric_Fence = ITEMS.register("orange_electric_fence", () -> new BlockItem(BlockInit.ORANGE_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        MAGENTA_Electric_Fence = ITEMS.register("magenta_electric_fence", () -> new BlockItem(BlockInit.MAGENTA_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIGHT_BLUE_Electric_Fence = ITEMS.register("light_blue_electric_fence", () -> new BlockItem(BlockInit.LIGHT_BLUE_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        YELLOW_Electric_Fence = ITEMS.register("yellow_electric_fence", () -> new BlockItem(BlockInit.YELLOW_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
        LIME_Electric_Fence = ITEMS.register("lime_electric_fence", () -> new BlockItem(BlockInit.LIME_Electric_Fence.get(), new Item.Properties().tab(Electricfencemod.electricfencemodTab.MAIN)));
    }

}
